### ISSUE TITLE
Webactivator Not Firing in Windows 7 iis 7.5

### ISSUE THREAD

**Issue by sarcjack** [davidebbo/WebActivator#27]
This just started happening this week so I'm not sure if it was an OS update that did it.

When I run a PostApplicationStartMethod it never fires on my local iis install, but it does fire if I run the sample application in IIS express out of visual studio. 

It's still working fine on other servers that run windows 2008 which should be the same IIS version. I am using it with windsor and glass mapper https://github.com/mikeedwards83/Glass.Mapper

I know they have taken out webactivator in the latest version because of debugging issues on specific servers, but I'd rather not take that drastic step if I don't have to.

**Comment by davidebbo** [comment]
To help isolate, have you checked whether `PreApplicationStartMethodAttribute` works?

**Comment by sarcjack** [comment]
I just tried switching it and PreApplicationStartMethodAttribute isn't running either. I can just hit the breakpoint Application_Start in global.asax. Again both breakpoints are hit in iis express.

**Comment by davidebbo** [comment]
Next thing: you should try the **ASP.NET** `PreApplicationStartMethodAttribute`. The one from WebActivator is named the same, but with a different namespace, and it builds over the underlying on. e.g. see this [post](http://haacked.com/archive/2010/05/16/three-hidden-extensibility-gems-in-asp-net-4.aspx/) which describes the ASP.NET feature.

If that one works, then it may be a WebActivator issue. OTOH, if that one doesn't work either, then WebActivator is off the hook, and it becomes an ASP.NET question (and hence is better discussed on ASP.NET forums).

**Comment by sarcjack** [comment]
Looks like the asp.net event isn't working either. That gives me more to go on thanks for your help. I'll post a reply if I find anything valuable

**Comment by davidebbo** [comment]
Sounds good. Closing here, but do follow up if you find what's happening, in case someone else runs into this.

Here is a thread, but with no clear solution: http://forums.asp.net/t/1924918.aspx?PreApplicationStartMethod+isn+t+work+anymore
