### ISSUE TITLE
WebActivatorEx 2.2.0 doesn't include FSharp.Core in its list of official dependencies

### ISSUE THREAD

**Issue by ghost** [davidebbo/WebActivator#30]
I think the new WebActivatorEx 2.2.0 now has a dependency on the FSharp.Core package.

If this is the case, shouldn't WebActivatorEx include FSharp.Core in its list of official dependencies?

For example, I deployed an application using WebActivatorEx on an environment where no FSharp assemblies were available and had a runtime crash. Yes, I could still add the FSharp package manually to each project, but then it would be easy to forget and could be misleading, leading into thinking FSharp is not being used by anything.

If WebActivator automatically pulled the FSharp.Core package as well, I believe this issue would have been covered.

I just don't want other devs to run into this issue in the future!

**Comment by davidebbo** [comment]
I don't think it has such dependency. Where specifically are you seeing this?

**Comment by davidebbo** [comment]
Closing until more info is provided. I'm quite sure there is no such dependency on anything related to F#, so I suspect it's a misunderstanding.

**Comment by ghost** [comment]
I saw WebActivatorEx in the stack trace of the error and just assumed it was the component using FSharp. Turns out it was another unrelated component. Sorry for the trouble, and many thanks for your quick response :)

**Comment by davidebbo** [comment]
np, glad you figured it out!
