### ISSUE TITLE
[Question] Is this deprecated? 

### ISSUE THREAD

**Issue by balab2020** [davidebbo/WebActivator#33]
We could see the below message in [nuget.org](https://www.nuget.org/packages/WebActivator).

> The owner has unlisted this package. This could mean that the package is deprecated or shouldn't be used anymore.

Is this really deprecated?

If yes, is there alternate proposal / official support announcement / road map on this ?

We are using this in our project and are being asked asked to check this binary survival ? 

Please suggest.

**Comment by davidebbo** [comment]
It was renamed to `WebActivatorEx` a few years ago. https://www.nuget.org/packages/WebActivatorEx

**Comment by davidebbo** [comment]
See also https://github.com/davidebbo/WebActivator/wiki/Signing-WebActivator

**Comment by balab2020** [comment]
@davidebbo thanks for update
